// flow-typed signature: af5c3558aaa9f0c96916800cfaa6ba47
// flow-typed version: <<STUB>>/livejournal_v0.1.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'livejournal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'livejournal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'livejournal/lib/api' {
  declare module.exports: any;
}

declare module 'livejournal/lib/jsonrpc' {
  declare module.exports: any;
}

declare module 'livejournal/lib/utils/getFacebookStats' {
  declare module.exports: any;
}

declare module 'livejournal/lib/utils/parseLink' {
  declare module.exports: any;
}

declare module 'livejournal/lib/xmlrpc' {
  declare module.exports: any;
}

declare module 'livejournal/spec/apiSpec' {
  declare module.exports: any;
}

declare module 'livejournal/spec/jsonRPCSpec' {
  declare module.exports: any;
}

declare module 'livejournal/spec/utilsSpec/getFacebookStatsSpec' {
  declare module.exports: any;
}

declare module 'livejournal/spec/utilsSpec/parseLinkSpec' {
  declare module.exports: any;
}

declare module 'livejournal/spec/xmlrpcSpec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'livejournal/index' {
  declare module.exports: $Exports<'livejournal'>;
}
declare module 'livejournal/index.js' {
  declare module.exports: $Exports<'livejournal'>;
}
declare module 'livejournal/lib/api.js' {
  declare module.exports: $Exports<'livejournal/lib/api'>;
}
declare module 'livejournal/lib/jsonrpc.js' {
  declare module.exports: $Exports<'livejournal/lib/jsonrpc'>;
}
declare module 'livejournal/lib/utils/getFacebookStats.js' {
  declare module.exports: $Exports<'livejournal/lib/utils/getFacebookStats'>;
}
declare module 'livejournal/lib/utils/parseLink.js' {
  declare module.exports: $Exports<'livejournal/lib/utils/parseLink'>;
}
declare module 'livejournal/lib/xmlrpc.js' {
  declare module.exports: $Exports<'livejournal/lib/xmlrpc'>;
}
declare module 'livejournal/spec/apiSpec.js' {
  declare module.exports: $Exports<'livejournal/spec/apiSpec'>;
}
declare module 'livejournal/spec/jsonRPCSpec.js' {
  declare module.exports: $Exports<'livejournal/spec/jsonRPCSpec'>;
}
declare module 'livejournal/spec/utilsSpec/getFacebookStatsSpec.js' {
  declare module.exports: $Exports<'livejournal/spec/utilsSpec/getFacebookStatsSpec'>;
}
declare module 'livejournal/spec/utilsSpec/parseLinkSpec.js' {
  declare module.exports: $Exports<'livejournal/spec/utilsSpec/parseLinkSpec'>;
}
declare module 'livejournal/spec/xmlrpcSpec.js' {
  declare module.exports: $Exports<'livejournal/spec/xmlrpcSpec'>;
}
