// flow-typed signature: 3f183ee90301bdcbe6f012a689645e02
// flow-typed version: <<STUB>>/react-native-xmlrpc_v0.0.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-xmlrpc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-xmlrpc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-xmlrpc/lib/customtype' {
  declare module.exports: any;
}

declare module 'react-native-xmlrpc/lib/date_formatter' {
  declare module.exports: any;
}

declare module 'react-native-xmlrpc/lib/Deserializer' {
  declare module.exports: any;
}

declare module 'react-native-xmlrpc/lib/Serializer' {
  declare module.exports: any;
}

declare module 'react-native-xmlrpc/lib/xmlrpc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-xmlrpc/lib/customtype.js' {
  declare module.exports: $Exports<'react-native-xmlrpc/lib/customtype'>;
}
declare module 'react-native-xmlrpc/lib/date_formatter.js' {
  declare module.exports: $Exports<'react-native-xmlrpc/lib/date_formatter'>;
}
declare module 'react-native-xmlrpc/lib/Deserializer.js' {
  declare module.exports: $Exports<'react-native-xmlrpc/lib/Deserializer'>;
}
declare module 'react-native-xmlrpc/lib/Serializer.js' {
  declare module.exports: $Exports<'react-native-xmlrpc/lib/Serializer'>;
}
declare module 'react-native-xmlrpc/lib/xmlrpc.js' {
  declare module.exports: $Exports<'react-native-xmlrpc/lib/xmlrpc'>;
}
