// flow-typed signature: 64c9e843cae04c65f174f1ed501fdc21
// flow-typed version: <<STUB>>/react-native-custom-tabs_v0.1.7/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-custom-tabs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-custom-tabs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-custom-tabs/src/ChromeIOS' {
  declare module.exports: any;
}

declare module 'react-native-custom-tabs/src/CustomTabsAndroid' {
  declare module.exports: any;
}

declare module 'react-native-custom-tabs/src/decls/native-modules' {
  declare module.exports: any;
}

declare module 'react-native-custom-tabs/src/TabOption' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-custom-tabs/index' {
  declare module.exports: $Exports<'react-native-custom-tabs'>;
}
declare module 'react-native-custom-tabs/index.js' {
  declare module.exports: $Exports<'react-native-custom-tabs'>;
}
declare module 'react-native-custom-tabs/src/ChromeIOS.js' {
  declare module.exports: $Exports<'react-native-custom-tabs/src/ChromeIOS'>;
}
declare module 'react-native-custom-tabs/src/CustomTabsAndroid.js' {
  declare module.exports: $Exports<'react-native-custom-tabs/src/CustomTabsAndroid'>;
}
declare module 'react-native-custom-tabs/src/decls/native-modules.js' {
  declare module.exports: $Exports<'react-native-custom-tabs/src/decls/native-modules'>;
}
declare module 'react-native-custom-tabs/src/TabOption.js' {
  declare module.exports: $Exports<'react-native-custom-tabs/src/TabOption'>;
}
